---
- hosts: target
  tasks:
  - name: copy deployment file to kubernetes cluster
    copy:
      src: deployment.yaml
      dest: /home/ubuntu-worker/deploy/
  - name: create a deployment by reading the new deployment file
    shell: kubectl apply -f /home/ubuntu-worker/deploy/deployment.yaml
  